document.write('<header>');
document.write('        <div class="container">');
document.write('            <center><a href=""><h1>BD-OFFiCiAL</h1></a></center>');
document.write('            <!-- Search box -->');
document.write('            <div class="search-box">');
document.write('                <center><form action="" onsubmit="return false">');
document.write('                    <input type="text" id="search" placeholder="Search Product">');
document.write('                </form></center>');
document.write('            </div>');
document.write('            <!-- filter box 1-->');
document.write('            <div class="filter-box"><center>			');
document.write('                <a href="#" class="btn" data-filter="smart"><h2>Smart</h2></a>			');
document.write('                <a href="#" class="btn" data-filter="parisa"><h2>Parisa</h2></a>');
document.write('                <a href="#" class="btn" data-filter="tasmia"><h2>Tasmia</h2></a></center>                         ');
document.write('            <!-- filter box 2--> 			');
document.write('            <div class="filter-box"><center>			');
document.write('                <a href="#" class="btn" data-filter="brush"><h2>Brush</h2></a>			');
document.write('                <a href="#" class="btn" data-filter="gown"><h2>Cosmetics</h2></a>');
document.write('                <a href="#" class="btn" data-filter="jewelry"><h2>Others</h2></a></center>');
document.write('	         <!-- filter box 3--> 			');
document.write('            <div class="filter-box"><center>				');
document.write('				<a href="#" class="btn" data-filter="shirt"><h2>Clothes</h2></a>			');
document.write('                <a href="#" class="btn" data-filter="gown"><h2>Shoes</h2></a>');
document.write('                <a href="#" class="btn" data-filter="jewelry"><h2>Accessories</h2></a></center>');
document.write('            </div>');
document.write('        </div>');
document.write('    </header>');
