document.write(' <!-- product -->    ');
document.write('    <main>');
document.write('        <div class="slide-container">');
document.write('        <section class="container" id="store-products"><center>');
document.write('<!---1smart--------------------------------------------------------------------------------------------------->');
document.write('<!----items1------------->   	');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/1.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-MEHEDI(25gm)</h3>');
document.write('                    <p> <span>TK-</span> 50TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/2.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-CONE(30ml)</h3>');
document.write('                    <p> <span>TK-</span> TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/3.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-BLACK-GOLD(25gm)</h3>');
document.write('                    <p> <span>TK-</span> 55TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/4.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-NAIL(15gm)</h3>');
document.write('                    <p> <span>TK-</span> 35TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/5.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4>');
document.write('                    <h3>SMART-FACEWASH<br/>GREEN(70gm)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>                ');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/6.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4>                    ');
document.write('                    <h3>SMART-FACEWASH<br/>YELLOW(70gm)</h3>');
document.write('                    <p> <span>TK-</span> 85TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/7.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-HAIR-REMOVAL-PULPLE</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/8.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4>                      ');
document.write('                    <h3>SMART-HAIR-REMOVAL<br/>GREEN(25gm)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/9.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4>                      ');
document.write('                    <h3>SMART-HAIR-COLOR<br/>RED(40gm)</h3>');
document.write('                    <p><span>TK-</span> 50TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/10.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4>                     ');
document.write('                    <h3>SMART-HAIR-COLOR<br/>BROWN(50gm)</h3>');
document.write('                    <p><span>TK-</span> 50TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/11.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">                  ');
document.write('                    <h3>SMART-HAIR<br/>COLOR-BLACK</h3>');
document.write('                    <p> <span>55TK(45ml)-90(90ml)</span> <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>55TK(45ml)-90(90ml)</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/12.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h5><br/></h5>                      ');
document.write('                    <h3>SMART-POWDER</h3>');
document.write('                    <p><span>40TK(100gm)60TK(150gm)-</span> <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>40TK(100gm)60TK(150gm)</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/13.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-COOL-POWDER(100gm)</h3>');
document.write('                    <p> <span>TK-</span> 55TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/14.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4>                     ');
document.write('                    <h3>SMART-PRICKLY<br/>POWDER(100gm)</h3>');
document.write('                    <p> <span>TK-</span> 55TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('<div class="store-product smart">');
document.write('    <img width="1071" height="1071" loading="lazy" src="./products/1smart/15.jpg" class="gallery-item" alt="Gallery2">');
document.write('    <div class="product-details">');
document.write('        <h4><br/></h4>         ');
document.write('        <h3>SMART-BUAUTY<br/>POWDER(100gm)</h3>');
document.write('        <p> <span>TK-</span> 55TK</p>');
document.write('        ');
document.write('    </div><br />');
document.write('</div>            ');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/16.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-SHAMPOO-BLACK(6ml)</h3>');
document.write('                    <p> <span>TK-</span> 2TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/17.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-SHAMPOO-WHITE(6ml)</h3>');
document.write('                    <p> <span>TK-</span> 3TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/18.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h5><br/></h5>                ');
document.write('                    <h3>SMART-POWER-BAR</h3>');
document.write('                    <p> <span>30TK(300gm)10TK(100gm)-</span> <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>30TK(300gm)10TK(100gm)</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/19.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-LIQUID-SMALL(250ml)</h3>');
document.write('                    <p> <span>TK-</span> TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/20.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-LIQUID-BIG(500ml)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/21.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-LIQUID-YELLOW(500ml)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br/>');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/22.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-LIQUID-NEW(500ml)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/23.png" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3>SMART-LOTION</h3>');
document.write('                    <p> <span>TK-</span> TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/24.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3>SMART-SKIN-LOTTION(150ml)(200ml)</h3>');
document.write('                    <p> <span>TK-</span> TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/25.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4> ');
document.write('                    <h3>SMART-HANDWASH<br/>GREEN(250ml)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/26.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4>                     ');
document.write('                    <h3>SMART-HANDWASH<br/>RED(250ml)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/27.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4>                     ');
document.write('                    <h3>SMART-HANDWASH<br/>YELLOW(250ml)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/28.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h5><br/></h5>                      ');
document.write('                    <h3>SMART-LIQUID-BLUE</h3>                   ');
document.write('                    <p> <span>TK</span> <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>16TK(40ml)22TK(75ml)</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/29.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h3><br/>SMART-WINTER-CARE(15ml)</h3>');
document.write('                    <p> <span>TK-</span> 20TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items1------------->                      ');
document.write('            <div class="store-product smart">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/1smart/30.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h5><br/></h5>                    ');
document.write('                    <h3>SMART-LIPJELL(15ml)(50ml)</h3>');
document.write('                    <p> <span>TK-</span> TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!---2parisa-------------------------------------------------------------------------------------------------->');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/1.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h5><br/></h5>                                        ');
document.write('                    <h3>ROBI-DETERGRNT-POWDER</h3>');
document.write('                    <p> <span>TK</span> <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>60TK(500gm)25TK(200GM)</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/2.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">                   ');
document.write('                    <h3><br/>PARISA-MAHEDI(25gm)</h3>');
document.write('                    <p> <span>TK-</span> 50TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/3.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details"> ');
document.write('                    <h5><br/></h5>                                      ');
document.write('                    <h3>PARISA-NEEM-FACEWASH</h3>');
document.write('                    <p> <span>TK</span> <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>100TK(70gm)150TK(100gm)</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/4.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">                   ');
document.write('                    <h3><br/>PARISA-HAIR-REMOVAL(25gm)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/5.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4>                                        ');
document.write('                    <h3>PARISA-HAIR-REMOVAL<br/>ROSE(25gm)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/6.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4>                                       ');
document.write('                    <h3>PARISA-HAIR-COLOR<br/>RED(40gm)</h3>');
document.write('                    <p> <span>TK-</span> 50TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/7.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">  ');
document.write('                    <h4><br/></h4>                                      ');
document.write('                    <h3>PARISA-HAIR-COLOR-BROWN(10gm)(20gm)</h3>');
document.write('                    <p> <span>TK-</span> TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/8.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details"> ');
document.write('                    <h4><br/></h4>                                      ');
document.write('                    <h3>PARISA-DISHWASH<br/>LIQUID(500ml)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/9.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">   ');
document.write('                    <h5><br/></h5>                                    ');
document.write('                    <h3>PARISA-SKIN-LOTION</h3>');
document.write('                    <p> <span>TK-</span> <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>90TK(100ml)140TK(200ml)</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/10.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details"> ');
document.write('                    <h4><br/></h4>                                      ');
document.write('                    <h3>PARISA-HAND-WASH<br/>GREEN(250ml)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/11.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details"> ');
document.write('                    <h4><br/></h4>                                      ');
document.write('                    <h3>PARISA-HAND-WASH<br/>YELLOW(250ml)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!----items2------------->');
document.write('           <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/12.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h4><br/></h4>                                       ');
document.write('                    <h3>PARISA-HAND-WASH<br/>RED(250ml)</h3>');
document.write('                    <p> <span>TK-</span> 90TK</p>');
document.write('        ');
document.write('    </div><br />');
document.write('</div>');
document.write('<!----items2------------->');
document.write('            <div class="store-product parisa">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/2parisa/13.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">                   ');
document.write('                    <h3>PARISA-LIPJELL(15ml)(50ml)</h3>');
document.write('                    <p> <span>TK-</span> TK</p>');
document.write('                    ');
document.write('                </div><br />');
document.write('            </div>');
document.write('<!---3tasmia-------------------------------------------------------------------------------------------------->');
document.write('<!----items3------------->');
document.write('            <div class="store-product tasmia">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/3tasmia/1.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h5><br/></h5>                                       ');
document.write('                    <h3>ROCKET-DETERGRNT-POWDER</h3>');
document.write('                    <p> <span>TK-</span> <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>60TK(500gm)25TK(200gm)</p>');
document.write('        ');
document.write('                </div><br />');
document.write('            </div>    ');
document.write('<!----items3------------->');
document.write('            <div class="store-product tasmia">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/3tasmia/2.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">');
document.write('                    <h5><br/></h5>                                       ');
document.write('                    <h3>GREEN-LEAF-FACE-WASH</h3>');
document.write('                    <p> <span>TK-</span> <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>110TK(70gm)150TK(100gm)</p>');
document.write('        ');
document.write('                </div><br />');
document.write('            </div>  ');
document.write('<!----items3------------->');
document.write('            <div class="store-product tasmia">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/3tasmia/3.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details"> ');
document.write('                    <h5><br/></h5>                                      ');
document.write('                    <h3>TASMIA-COLL-OIL</h3>');
document.write('                    <p> <span>TK-</span> <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>55TK(50ml)95TK(100ml)</p>');
document.write('        ');
document.write('                </div><br />');
document.write('            </div>  ');
document.write('<!----items3------------->');
document.write('            <div class="store-product tasmia">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/3tasmia/4.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">                   ');
document.write('                    <h3><br/>TASMIA-PRICKLY-POWDER(100gm)</h3>');
document.write('                    <p> <span>TK-</span> 55TK</p>');
document.write('        ');
document.write('                </div><br />');
document.write('            </div>  ');
document.write('<!----items3------------->');
document.write('            <div class="store-product tasmia">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/3tasmia/5.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">                   ');
document.write('                    <h3><br/>TASMIA-COOL-POWDER(100gm)</h3>');
document.write('                    <p> <span>TK-</span> 55TK</p>');
document.write('        ');
document.write('                </div><br />');
document.write('            </div>  ');
document.write('<!----items3------------->');
document.write('            <div class="store-product tasmia">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/3tasmia/6.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">                   ');
document.write('                    <h3><br/>TASMIA-DISHWASH-LIQUID(250ml)</h3>');
document.write('                    <p> <span>TK-</span> 40TK</p>');
document.write('        ');
document.write('                </div><br />');
document.write('            </div>  ');
document.write('<!----items3------------->');
document.write('            <div class="store-product tasmia">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/3tasmia/7.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">                   ');
document.write('                    <h3><br/>TASMIA-DISHWASH-LIQUID(500ml)</h3>');
document.write('                    <p> <span>TK-</span> TK</p>');
document.write('        ');
document.write('                </div><br/>');
document.write('            </div>  ');
document.write('<!----items3------------->');
document.write('            <div class="store-product tasmia">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/3tasmia/8.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">                   ');
document.write('                    <h3>TASMIA-KITCHEN-BAR</h3>');
document.write('                    <p> <span>TK-</span> TK</p>');
document.write('        ');
document.write('                </div><br />');
document.write('            </div>  ');
document.write('<!----items3------------->');
document.write('            <div class="store-product tasmia">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/3tasmia/9.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">                   ');
document.write('                    <h3>TASMIA-BLUE</h3>');
document.write('                    <p> <span>TK-</span> TK</p>');
document.write('        ');
document.write('                </div><br />');
document.write('            </div>  ');
document.write('<!----items3------------->');
document.write('            <div class="store-product tasmia">');
document.write('                <img width="1071" height="1071" loading="lazy" src="./products/3tasmia/10.jpg" class="gallery-item" alt="Gallery2">');
document.write('                <div class="product-details">                   ');
document.write('                    <h3>TASMIA-BEAUTY-POMED</h3>');
document.write('                    <p> <span>TK-</span> TK</p>');
document.write('        ');
document.write('                </div><br />');
document.write('            </div>  ');
document.write('<!-- male shirts ---------------------------------------------------->	');
document.write('        <div class="store-product shirt">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/ms1.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>Shirt Product</h3>');
document.write('                <p> <span>500TK-</span> 280TK</p>');
document.write('				');
document.write('            </div><br />');
document.write('        </div>			');
document.write('        <div class="store-product shirt">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/ms2.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>Shirt Product</h3>');
document.write('                <p> <span>500TK-</span> 280TK</p>');
document.write('				');
document.write('            </div><br />');
document.write('        </div>');
document.write('        <div class="store-product shirt">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/ms3.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>Shirt Product</h3>');
document.write('                <p> <span>500TK-</span> 280TK</p>');
document.write('				');
document.write('            </div><br />');
document.write('        </div>');
document.write('            <!-- brush----------------------------------------------------->			');
document.write('	    <div class="store-product brush">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/brush1.png" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>BRUSH-5433</h3>');
document.write('                <p> <span>20TK-</span> 50TK</p>');
document.write('');
document.write('            </div><br />');
document.write('        </div>');
document.write('	');
document.write('            <!-- male shoes------------------------------------------------------>			');
document.write('		<div class="store-product gown">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/msh1.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>SHOES</h3>');
document.write('                <p> <span>1300TK-</span> $1000TK</p>');
document.write('			');
document.write('            </div><br />');
document.write('        </div>');
document.write('		<div class="store-product gown">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/msh2.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>SHOES</h3>');
document.write('                <p> <span>1300TK-</span> $1000TK</p>');
document.write('				');
document.write('            </div><br />');
document.write('        </div>	');
document.write('		<div class="store-product gown">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/msh3.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>SHOES</h3>');
document.write('                <p> <span>1000TK-</span> 700TK</p>');
document.write('				');
document.write('            </div><br />');
document.write('        </div>');
document.write('		<div class="store-product gown">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/msh4.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>SHOES</h3>');
document.write('                <p> <span>350TK-</span> 200TK</p>');
document.write('				');
document.write('            </div><br />');
document.write('        </div>');
document.write('		<div class="store-product gown">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/msh5.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>SHOES</h3>');
document.write('                <p> <span>350TK-</span> 200TK</p>');
document.write('				');
document.write('            </div><br />');
document.write('        </div>');
document.write('		<div class="store-product gown">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/msh6.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>SHOES</h3>');
document.write('                <p> <span>350TK-</span> 200TK</p>');
document.write('			');
document.write('            </div><br />');
document.write('        </div>');
document.write('		<div class="store-product gown">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/msh7.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>SHOES</h3>');
document.write('                <p> <span>350TK-</span> 200TK</p>');
document.write('			');
document.write('            </div><br />');
document.write('        </div>');
document.write('		<div class="store-product gown">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/msh8.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>SHOES</h3>');
document.write('                <p> <span>400TK-</span> 300TK</p>');
document.write('				');
document.write('            </div><br />');
document.write('        </div>	');
document.write('		<div class="store-product gown">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/msh9.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>SHOES</h3>');
document.write('                <p> <span>400TK-</span> 300TK</p>');
document.write('				');
document.write('            </div><br />');
document.write('        </div>');
document.write('		<div class="store-product gown">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/msh10.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>SHOES</h3>');
document.write('                <p> <span>350TK-</span> 200TK</p>');
document.write('				');
document.write('            </div><br />');
document.write('        </div>	');
document.write('            <!-- accessaries----------------------------------------------------->			');
document.write('	    <div class="store-product jewelry">');
document.write('            <img width="1071" height="1071" loading="lazy" src="./images/ma1.webp" class="gallery-item" alt="Gallery2">');
document.write('            <div class="product-details">');
document.write('                <h3>MAPLEL FOR WINTER</h3>');
document.write('                <p> <span>150TK-</span> 100TK</p>');
document.write('');
document.write('            </div><br />');
document.write('        </div>');
document.write('    </center></section>');
document.write('</div>		');
document.write('            <!-- edit popup image -->');
document.write('<!-- Modal -->');
document.write('<div class="modal fade" id="gallery-popup" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">');
document.write('  <div class="modal-dialog modal-dialog-centered modal-lg">');
document.write('    <div class="modal-content">');
document.write('      <div class="modal-body">');
document.write('        <img src="images/1.jpg" class="modal-img" alt="Modal Image">');
document.write('      </div>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>    ');
document.write('            <!-- 000 -->');
document.write('</main>');
document.write('    <script src="./js/scriptfilter.js"></script>	');
document.write('            <!-- edit popup imagr -->');
document.write('	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>');
document.write('	<script type="text/javascript">');
document.write('		document.addEventListener("click",function (e){');
document.write('		  if(e.target.classList.contains("gallery-item")){');
document.write('		  	  const src = e.target.getAttribute("src");');
document.write('		  	  document.querySelector(".modal-img").src = src;');
document.write('		  	  const myModal = new bootstrap.Modal(document.getElementById(\'gallery-popup\'));');
document.write('		  	  myModal.show();');
document.write('		  }');
document.write('		})');
document.write('	</script>	');
