document.write('<head>  ');
document.write('<!-- ====== Favicon ====== -->');
document.write('<link');
document.write('rel="shortcut icon"');
document.write('href="icons/icon.png"');
document.write('type="image/png"/>');
document.write('<!--NEW ZOOM-->');
document.write('<meta name="color-scheme"content="dark">');
document.write('<meta name="viewport" content="width=device-width,user-scalable=no, initial-scale=1.0"/>    ');
document.write('<!-- boststrap-offline-->');
document.write('<link rel="stylesheet" type="text/css" href="./css/bootstrap.min.css">	');
document.write('<!--EndEditable calcu-->');
document.write('<link rel="stylesheet" href="./css/chat.css">');
document.write('<script src="js/calculator.js" type="text/javascript"></script>   ');
document.write('<!---CSS--->');
document.write('<link rel="stylesheet" href="./css/stylesfilter.css">');
document.write('<!-- TITLE -->');
document.write('  <title>Products</title>     ');
document.write('</head>');
