document.write('<header> ');
document.write('        <div class="container">');
document.write('            <center><a><h1>BD-OFFiCiAL</h1></a></center>');
document.write('            <!-- Search box -->');
document.write('            <div class="search-box">');
document.write('                <center><form action="" onsubmit="return false">');
document.write('                    <input id="search" placeholder="Search Product">');
document.write('                </form></center>');
document.write('            </div>');
document.write('            <!-- filter box 1-->');
document.write('  <center><div class="filter-box">');
document.write(' <a href="#" class="btn"data-filter="BODY-SOAP"><h2>BODY-SOAP</h2></a>');
document.write(' <a href="#" class="btn"data-filter="face-wash"><h2>FACE-WASH</h2></a>');
document.write(' <a href="#"class="btn"data-filter="cream"><h2>CREAM</h2></a>	');
document.write(' <a href="#" class="btn"data-filter="shampoo"><h2>&nbsp;SHAMPOO</h2></a>	<a href="#" class="btn"data-filter="hair-oil"><h2>HAIR-OIL</h2></a>');
document.write(' <a href="#" class="btn"data-filter="perfume"><h2>PERFUME</h2></a>');
document.write(' <a href="#" class="btn"data-filter="seasonal"><h2>&nbsp;SEASONAL</h2></a>');
document.write(' <a href="#" class="btn"data-filter="cleaning"><h2>CLEANING</h2></a>');
document.write(' <a href="#" class="btn"data-filter="other"><h2>OTHER</h2></a>');
document.write('      </div></center>');
document.write('      </div></header>');
