document.write('<header> ');
document.write('        <div class="container">');
document.write('            <center><a><h1>BD-OFFiCiAL</h1></a></center>');
document.write('            <!-- Search box -->');
document.write('            <div class="search-box">');
document.write('                <center><form action="" onsubmit="return false">');
document.write('                    <input id="search" placeholder="Search Product">');
document.write('                </form></center>');
document.write('            </div>');
document.write('            <!-- filter box 1-->');
document.write('  <center><div class="filter-box">');
document.write(' <a href="#" class="btn"data-filter="COSMETICS"><h2>COSMETICS</h2></a>');
document.write(' <a href="#" class="btn"data-filter="FOODS"><h2>FOODS</h2></a>');
document.write(' <a href="#"class="btn"data-filter="VARIETIES"><h2>VARIETIES</h2></a>	');
document.write('      </div></center>');
document.write('      </div></header>');
