document.write('<main>      ');
document.write('            <!--product id -->    ');
document.write('        <div class="slide-container">');
document.write('        <section class="container" id="store-products"><center>');
document.write('<!----1COSMETICS--------------------------------------------------1-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>JOHNSON\'S BABY SOAP 75gm</h3>');
document.write('    <a href="./products/1/1.webp" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="JOHNSON\'S-BABY-SOAP(65gm)" disabled></a>');
document.write('    <p><span>1560(130)TK-</span>960(80)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a11">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b11()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>                 ');
document.write('<!----1COSMETICS--------------------------------------------------2-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>DETOL SOAP 75gm</h3>');
document.write('    <a href="./products/1/2.webp" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="DETOL-SOAP(75gm)" disabled></a>');
document.write('    <p><span>600(50)TK-</span>540(45)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a12">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b12()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----2COSMETICS--------------------------------------------------1-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>CLEAN & CLEAR 50ml clean and clear</h3>');
document.write('    <a href="./products/2/1.jpg" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="CLEAN-&-CLEAR(50ml)" disabled></a>');
document.write('    <p><span>1608(134)TK-</span>986.4(82.5)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a21">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b21()" />');
document.write('    </form> ');
document.write('  </div>');
document.write('</div>');
document.write('<!----2COSMETICS--------------------------------------------------102-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>CLEAN & CLEAR 100ml clean and clear</h3>');
document.write('    <a href="./products/2/1.jpg" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="CLEAN-&-CLEAR(100ml)" disabled></a>');
document.write('    <p><span>2748(229)TK-</span>1716(143)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a2102">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b2102()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div> ');
document.write('<!----2COSMETICS--------------------------------------------------2-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>HIMALAYA FACE WASH 50ml</h3>');
document.write('    <a href="./products/2/2.jpeg" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="HIMALAYA-COSMETICS(50ml)" disabled></a>');
document.write('    <p><span>1320(110)TK-</span>840(70)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a22">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b22()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div> ');
document.write('<!----2COSMETICS--------------------------------------------------202-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>HIMALAYA FACE WASH 100ml</h3>');
document.write('    <a href="./products/2/2.jpeg" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="HIMALAYA-COSMETICS(100ml)" disabled></a>');
document.write('    <p><span>2640(220)TK-</span>1080(90)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a2202">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b2202()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>    ');
document.write('<!----2COSMETICS--------------------------------------------------5');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>YC FACE WASH 100ml</h3>');
document.write('    <a href="./products/2/3.webp" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="YC-COSMETICS(100ml)" disabled></a>');
document.write('    <p><span>()TK-</span>()TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a25">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b25()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>          ');
document.write('<!----3COSMETICS--------------------------------------------------1-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>JOHNSON\'S MILK COSMETICS 50gm</h3>');
document.write('   <a href="./products/3/1.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="JOHNSON\'S-MILK-COSMETICS(50gm)" disabled></a>');
document.write('   <p><span>2400(200)TK-</span>1680(140)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a31">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b31()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----3COSMETICS--------------------------------------------------2-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>LOTA HARBAL 20gm</h3>');
document.write('   <a href="./products/3/1.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="LOTA-HARBAL(20gm)" disabled></a>');
document.write('   <p><span>600(50)TK-</span>450(37.5)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a32">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b32()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----3COSMETICS--------------------------------------------------3-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>SKIN SHINE 30gm</h3>');
document.write('   <a href="./products/3/2.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="SKIN-SHINE(30gm)" disabled></a>');
document.write('   <p><span>1740(145)TK-</span>600(50)TK</p>');
document.write('    <form>');
document.write('      <input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a33">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b33()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----4COSMETICS--------------------------------------------------1-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>JOHNSON\'S COSMETICS 100ml</h3>');
document.write('   <a href="./products/4/1.webp"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="JOHNSON\'S-COSMETICS(100ml)" disabled></a>');
document.write('  <p><span>2400(200)TK-</span>1560(130)TK</p>');
document.write('    <form>');
document.write('      <input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a41">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b41()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----4COSMETICS--------------------------------------------------2-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>KATALIA COSMETICS</h3>');
document.write('   <a href="./products/4/2.webp"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="KATALIA-COSMETICS" disabled></a>');
document.write('  <p><span>10(1)TK-</span>9(0.75)TK</p>');
document.write('    <form>');
document.write('      <input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a42">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b42()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----5COSMETICS--------------------------------------------------1-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>SMART KESH KALA 45ml</h3>');
document.write('    <a href="./products/smart/11.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="SMART-KESH-KALA(45ml)" disabled></a>');
document.write('    <p> <span>660(55)TK-</span>420(35)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a51">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b51()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----5COSMETICS--------------------------------------------------2-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>KUMARIKA HAIR OIL 100ml</h3>');
document.write('    <a href="./products/5/1.webp" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="KUMARIKA-COSMETICS(100ml)" disabled></a>');
document.write('    <p><span>1140(95)TK-</span>780(65)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a52">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b52()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----5COSMETICS--------------------------------------------------202-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>KUMARIKA HAIR OIL 200ml</h3>');
document.write('    <a href="./products/5/1.webp"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="KUMARIKA-COSMETICS(200ml)" disabled></a>');
document.write('    <p><span>2100(175)TK-</span>1500(125)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a5202">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b5202()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----6COSMETICS--------------------------------------------------1-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>FOGG COSMETICS 120ml</h3>');
document.write('    <a href="./products/6/2.webp" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="FOGG-COSMETICS(120ml)" disabled></a>');
document.write('    <p><span>3600(300)TK-</span>2880(240)TK</p>');
document.write('    <form>');
document.write('      <input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a61">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b61()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----6COSMETICS--------------------------------------------------2-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>KS COSMETICS 40ml</h3>');
document.write('    <a href="./products/6/3.webp" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="KS-COSMETICS(40ml)" disabled></a>');
document.write('    <p><span>2400(200)TK-</span>1680(140)TK</p>');
document.write('    <form>');
document.write('      <input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a62">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b62()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----6COSMETICS--------------------------------------------------202-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>KS COSMETICS 60ml</h3>');
document.write('    <a href="./products/6/4.webp" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="KS-COSMETICS(60ml)" disabled></a>');
document.write('    <p><span>3000(250)TK-</span>1920(160)TK</p>');
document.write('    <form>');
document.write('      <input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a6202">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b6202()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----6COSMETICS--------------------------------------------------3--> ');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>TOUCH ME 40ml</h3>');
document.write('   <a href="./products/6/1.webp"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="TOUCH-ME(40ml)" disabled></a>');
document.write('   <p><span>2400(200)TK-</span>1680(140)TK</p>');
document.write('    <form>');
document.write('      <input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a63">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b63()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----6COSMETICS--------------------------------------------------4--> ');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>COLOUR ME 60ml</h3>');
document.write('    <a href="./products/6/5.webp" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="COLOUR-ME(60ml)" disabled></a>');
document.write('    <p><span>3000(250)TK-</span>1920(160)TK</p>');
document.write('    <form>');
document.write('      <input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a64">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b64()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----7COSMETICS--------------------------------------------------4-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>SMART COOL POWDER 100gm</h3>');
document.write('    <a href="./products/smart/13.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="SMART-COOL-POWDER(100gm)" disabled></a>');
document.write('    <p> <span>660(55)TK-</span>480(40)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a74">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b74()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----7COSMETICS--------------------------------------------------5-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>SMART PRICKLY POWDER 100gm</h3>');
document.write('    <a href="./products/smart/14.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="SMART-PRICKLY-POWDER(100gm)" disabled></a>');
document.write('    <p> <span>660(55)TK-</span>480(40)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a75">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b75()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----7COSMETICS--------------------------------------------------6-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>SMART BUAUTY POWDER 100gm</h3>');
document.write('    <a href="./products/smart/15.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="SMART-BUAUTY-POWDER(100gm)" disabled></a>');
document.write('    <p> <span>660(55)TK-</span>450(37.5)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a76">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b76()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----7COSMETICS-------------------1-->');
document.write(' <div class="store-product COSMETICS">');
document.write(' <div class="product-details">');
document.write(' <h3 hidden>SMART TUBE 25gm</h3>');
document.write(' <a href="./products/smart/1.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;"value="SMART-TUBE(25gm)"disabled></a>');
document.write(' <p> <span>600(50)TK-</span>270(22.5)TK</p> ');
document.write(' <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a71">');
document.write(' <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('   margin-top:-16.4px;"');
document.write('   onclick="b71()"/></form>');
document.write(' </div>');
document.write(' </div>  ');
document.write('<!----7COSMETICS------------------2-->');
document.write(' <div class="store-product COSMETICS">');
document.write(' <div class="product-details">');
document.write(' <h3 hidden>SMART CONE 30gm</h3>');
document.write(' <a href="./products/smart/2.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;"value="SMART-CONE(30ml)"disabled></a>');
document.write(' <p> <span>780(65)TK-</span>430(35.83)TK)</p> ');
document.write(' <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a72">');
document.write(' <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('   margin-top:-16.4px;"');
document.write('   onclick="b72()"/></form>');
document.write(' </div>');
document.write(' </div>     ');
document.write('<!----7COSMETICS--------------------------------------------------3-->                    ');
document.write(' <div class="store-product COSMETICS">');
document.write(' <div class="product-details">');
document.write(' <h3 hidden>kashmeri cone 20gm</h3>');
document.write(' <a href="./products/smart/3.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;"value="KASHMERI-CONE(15gm)"disabled></a>');
document.write(' <p> <span>360(30)TK-</span>220(18.33)TK</p> ');
document.write(' <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a73">');
document.write(' <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('   margin-top:-16.4px;"');
document.write('   onclick="b73()"/></form>');
document.write(' </div>');
document.write(' </div>    ');
document.write(' <!----9other--------------------------------------------------1-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>SMART HAIR COLOR BROWN 50gm</h3>');
document.write('    <a href="./products/smart/10.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="SMART-HAIR-COLOR-BROWN(50gm)" disabled></a>');
document.write('    <p> <span>300(15)TK-</span>120(10)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a91">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b91()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----9other--------------------------------------------------2-->');
document.write('<div class="store-product COSMETICS">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>REXONA 50ml</h3>');
document.write('    <a href="./products/9/1.webp"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="REXONA(50ml)" disabled></a>');
document.write('    <p> <span>2160(180)TK-</span>1680(140)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a92">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b92()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write(' <!----8VARIETIES--------------------------------------------------1-->');
document.write('<div class="store-product VARIETIES">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>SMART POWER BAR 10gm</h3>');
document.write('    <a href="./products/smart/18.jpg" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="SMART-POWER-BAR(10gm)" disabled></a>');
document.write('    <p> <span>120(10)TK-</span>100(8.33)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a11">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('   margin-top:-16.4px;" onclick="b11()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----8VARIETIES--------------------------------------------------2-->');
document.write('<div class="store-product VARIETIES">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>SMART POWER BAR 30gm</h3>');
document.write('    <a href="./products/smart/18.jpg" target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="SMART-POWER-BAR(30gm)" disabled></a>');
document.write('    <p><span>360(30)TK-</span>300(25)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a12">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('   margin-top:-16.4px;" onclick="b12()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----8VARIETIES--------------------------------------------------3-->');
document.write('<div class="store-product VARIETIES">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>SMART LIQUID 500ml</h3>');
document.write('   <a href="./products/smart/22.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;"value="SMART-LIQUID(500ml)" disabled></a>');
document.write('   <p><span>1320(110)TK-</span>840(70)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a81">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b81()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----8VARIETIES--------------------------------------------------4-->');
document.write('<div class="store-product VARIETIES">');
document.write('  <div class="product-details">');
document.write('  <h3 hidden>SMART BLUE 50ML</h3>');
document.write('   <a href="./products/smart/28.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="SMART-BLUE(50ml)" disabled></a>');
document.write('   <p><span>180(15)TK-</span>150(12.5)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a82">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b82()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----8VARIETIES--------------------------------------------------5-->');
document.write('<div class="store-product VARIETIES">');
document.write('  <div class="product-details">');
document.write(' <h3 hidden>SMART BLUE 100ML</h3>');
document.write('    <a href="./products/smart/28.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="SMART-BLUE(100ml)" disabled></a>');
document.write('    <p><span>360(30)TK-</span>300(25)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a83">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b83()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write(' <!----8VARIETIES--------------------------------------------------6-->');
document.write('<div class="store-product VARIETIES">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>ROBI DETERGRNT POWDER 200gm</h3>');
document.write('    <a href="./products/smart/31.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="DETERGRNT-POWDER(200gm)" disabled></a>');
document.write('    <p> <span>300(25)TK-</span>240(20)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a84">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b84()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----8VARIETIES--------------------------------------------------7-->');
document.write('<div class="store-product VARIETIES">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>ROBI DETERGRNT POWDER 500gm</h3>');
document.write('    <a href="./products/smart/31.jpg"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="DETERGRNT-POWDER(500gm)" disabled></a>');
document.write('    <p> <span>720(60)TK-</span>540(45)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a85">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b85()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----8VARIETIES--------------------------------------------------8-->');
document.write('<div class="store-product VARIETIES">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>VIXOL 1000ml</h3>');
document.write('    <a href="./products/8/1.webp"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="VIXOL(1000ml)" disabled></a>');
document.write('    <p> <span>1440(120)TK-</span>960(80)TK</p>');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a88">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b88()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('<!----8VARIETIES--------------------------------------------------9-->');
document.write('<div class="store-product VARIETIES">');
document.write('  <div class="product-details">');
document.write('    <h3 hidden>HERPIC 750ml</h3>');
document.write('    <a href="./products/8/2.webp"target="_blank"><input class="form-control" style="text-align:center;background-color:green; color:#ffffff;" value="HERPIC(750ml)" disabled></a>');
document.write('    <p> <span>1680(140)TK-</span>1080(90)TK</p> ');
document.write('    <form><input type="number" style="text-align:center;background-color:#141415; color:white" class="form-control" id="a89">');
document.write('      <input class="form-control" value="SUBMIT" type="reset" style="background-color:rgb(238, 88, 62); color:#ffffff;');
document.write('                   margin-top:-16.4px;" onclick="b89()" />');
document.write('    </form>');
document.write('  </div>');
document.write('</div>');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('            <!-- 000 -->');
document.write('            <!-- 000 -->');
document.write('            <!-- 000 -->');
document.write('</center></section></div></main>');
